---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(DT)
library(echarts4r)
library(dplyr)
library(lubridate)
library(stringr) 
library(Hmisc)

options(encoding = "UTF-8")
e_theme_register('{"color":["#0791b7","#dad944","#cccccc", "#fb5057","#47c1ff","#f2b3c9"]}', name = "myTheme")

files <- list.files(path = 'data/', pattern = '.rds', full.names = TRUE)
sapl_data <- do.call("bind_rows", lapply(files, readRDS)) 
agrupamento_status <- read.table('agrupamento_status.txt', sep = '\t', header = TRUE) %>% as_tibble()

sapl_data <- inner_join(agrupamento_status, sapl_data, by = 'status')

sapl_data$Grupo <- recode_factor(as.factor(sapl_data$Grupo),
                                 '1' = 'Proposição Aprovada',
                                 '2' = 'Proposição Rejeitada',
                                 '3' = 'Em tramitação',
                                 '4' = 'Proposição Arquivada',
                                 'NA' = 'NA')
```


# Page 1

Row 
--------------------------------
### Matérias apresentadas por ano {data-width=800}
```{r}
    sapl_data %>% 
      count(ano_apresentacao) %>% 
      mutate(cond = ifelse(ano_apresentacao == year(Sys.time()), 'blue', 'grey')) %>% 
      group_by(cond) %>% 
      e_charts(x = ano_apresentacao) %>% 
      e_bar(n, emphasis = list(itemStyle = list(shadowBlur = 10)),
            itemStyle = list(borderRadius = 5), stack = TRUE) %>% 
      e_tooltip(formatter = htmlwidgets::JS("
                                        function(params)
                                        {
                                            return `<strong> ${params.value[0]} </strong>
                                                    <br/> 
                                                    Qtd. de matérias: ${params.value[1]}`
                                        }  ")) %>% 
      e_legend(show = FALSE) %>% 
      e_color(color = c('#0791b7', '#cccccc'))
```


### Chart B {data-width=200}

```{r}
    sapl_data %>% 
      filter(!is.na(Grupo)) %>%
      filter(projeto %nin% c('VT', 'VP', 'REQ', 'IND')) %>% 
      count(Grupo) %>% 
      mutate(prop = round(n*100/sum(n), 1)) %>% 
      e_charts(Grupo) %>% 
      e_pie(n, radius = c("50%", "70%")) %>% 
      e_tooltip(trigger = 'item') %>% 
      e_labels(FALSE)
```

Row 
-----------------------------------------------------------------------

### Chart C

```{r}
sapl_data %>%
      count(projeto) %>% 
      mutate(prop = round(n*100/sum(n), 1)) %>% 
      arrange(-desc(n)) %>% 
      e_charts(x = projeto) %>% 
      e_bar(serie = n,
            emphasis = list(itemStyle = list(shadowBlur = 10)),
            itemStyle = list(borderRadius = 5)) %>% 
      e_tooltip(trigger = 'axis') %>% 
      e_flip_coords() %>% 
      e_legend(show = FALSE)
```

### Chart D

```{r}
sapl_data %>% 
      # filter(ano_apresentacao %in% input$data,
      #        projeto %in% input$tipo) %>%
      mutate(autor = stringr::str_trim(autor)) %>% 
      count(autor) %>% 
      filter(!is.na(autor)) %>% 
      mutate(poder = NA) -> tabela_autoria
    
    for(i in 1:nrow(tabela_autoria)) {
      if(str_detect(tabela_autoria$autor[i], 'Defensoria Pública')) tabela_autoria[i, 'poder'] <- 'DPE'
      if(str_detect(tabela_autoria$autor[i], 'Tribunal De Contas')) tabela_autoria[i, 'poder'] <- 'TCE'
      if(str_detect(tabela_autoria$autor[i], 'Tribunal De Justiça')) tabela_autoria[i, 'poder'] <- 'Judiciário'
      if(str_detect(tabela_autoria$autor[i], 'Executivo')) tabela_autoria[i, 'poder'] <- 'Executivo'
    }  
    
    tabela_autoria$poder[is.na(tabela_autoria$poder)] <- 'Legislativo'
    tabela_autoria <- tabela_autoria %>% 
      as_tibble() %>% 
      rename(name = autor, value = n)
    
    tabela_poder <- tabela_autoria %>% 
      group_by(poder) %>% 
      summarise(value = sum(value)) %>% 
      rename(name = poder)
    
    tabela_poder %>% 
      #group_by(poder) %>%
      #group_nest() %>%
      mutate(value = tabela_poder$value) %>%
      # rename(name = poder,
      #        children = data) %>%
      e_charts() %>% 
      e_treemap(itemStyle = list(borderColor = 'white',
                                 borderWidth = 0.3)) %>% 
      e_tooltip(
        formatter = htmlwidgets::JS("
    function(params){
      return(params.name + ': ' + params.value);
    }
  ")) %>% 
      e_labels(position = 'insideTopLeft', 
               formatter = '{b}\n{c}')
```

### Chart E

```{r}
    sapl_data %>% 
      filter(projeto %in% c('VP', 'VT')) %>% 
      count(projeto) %>% 
      e_charts(projeto) %>% 
      e_pie(n, radius = c("50%", "70%")) %>% 
      e_tooltip(trigger = 'item') %>% 
      e_labels(FALSE)
```

# Page 2